include $(CLEAR_VARS)
LOCAL_MODULE       := loggy.sh
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_TAGS  := optional
LOCAL_SRC_FILES    := rootdir/bin/loggy.sh
LOCAL_MODULE_PATH  := $(TARGET_OUT_SYSTEM_EXECUTABLES)
include $(BUILD_PREBUILT)
